---
- name: Setup Exodata Server
  hosts: exodata
  become: yes

  vars_files:
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/leptos_env.yml

  roles:
    - common
    - docker
    - nginx
    - app
