# Domain configuration
domain: exodata.space
admin_email: alex@imscraping.ninja

# Docker image
docker_image: ghcr.io/oiwn/exoplanets-catalog
docker_tag: latest

# Application settings
app_name: exoplanets-catalog
app_port: 3000
data_path: /app/data

# Local data path (for upload-data playbook)
local_data_path: "{{ playbook_dir }}/../../../data/parquet"
