leptos_env:
  LEPTOS_OUTPUT_NAME: "exodata"
  LEPTOS_SITE_ROOT: "site"
  LEPTOS_SITE_PKG_DIR: "pkg"
  LEPTOS_SITE_ADDR: "0.0.0.0:3000"
  LEPTOS_ENV: "PROD"
  # Optional (Google Analytics):
  LEPTOS_GA_ID: ""
